# Generated by Django 5.2.8 on 2025-11-11 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfilusuario",
            options={
                "ordering": ["-fecha_contratacion"],
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.AlterModelOptions(
            name="proveedor",
            options={
                "ordering": ["empresa"],
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
            },
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="precio_venta",
            new_name="precio",
        ),
        migrations.RemoveField(
            model_name="proveedor",
            name="contacto",
        ),
        migrations.AddField(
            model_name="proveedor",
            name="direccion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="empresa",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
