# Generated by Django 5.2.8 on 2025-11-12 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_alter_perfilusuario_options_alter_producto_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={},
        ),
        migrations.RemoveField(
            model_name="producto",
            name="creado_por",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="proveedor",
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="tienda.categoria",
            ),
        ),
    ]
