# Generated by Django 5.2.8 on 2025-11-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0003_alter_producto_options_remove_producto_creado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="proveedores",
            field=models.ManyToManyField(blank=True, to="tienda.proveedor"),
        ),
    ]
