# Generated by Django 5.2.8 on 2025-11-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0005_cliente_usuario_alter_perfilusuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("vendedor", "Vendedor"),
                    ("gerente", "Gerente"),
                    ("administrador", "Administrador"),
                    ("cliente", "Cliente"),
                    ("admin", "Admin"),
                ],
                default="vendedor",
                max_length=20,
            ),
        ),
    ]
